export { clienteService } from './clienteService'
export type { Page } from './api'
export type { Cliente, ClienteForm, StatusCliente } from './clienteService'
export { prontuarioService } from './prontuarioService'
export type { Prontuario, StatusPaciente } from './prontuarioService'
export { evolucaoService } from './evolucaoService'
export type { Evolucao } from './evolucaoService'
export { agendamentoService } from './agendamentoService'
export type { Agendamento } from './agendamentoService'
